<a href="https://colab.research.google.com/github/sleevetug/Eloise/blob/main/Encode_Disability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests
import json

def get_data():
  url="https://qqlwlo6mlj.execute-api.eu-west-2.amazonaws.com/test/listening_data"
  query_data = {
      "query":"read_responders",
      "returnfields":[],
      "variables":{}
  }
  data = requests.post(url, data=json.dumps(query_data)).json()
  display(data)
  if 'success' in data.keys():
    return pd.json_normalize(data['success'])
  else:
    return None

df = get_data()
display(df)
if df is not None:

    def encode_disability(df, **kwds):

        df["disability"] = df["disability"].str.lower()

        key = kwds['key']

        if df[key] == "no":
          return 1
        else:
          return 0

    df["disability-encoded"] = df.apply(encode_disability, axis=1, key="disability")
    df

{'message': 'Internal server error'}

None

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

url = "https://drive.google.com/uc?export=download&id=144dlnCJ7rHs4LllVqXtsg2ABpnN_XucB"
df = pd.read_csv(url)

df = df[['Where are you based?', 'Which age range are you in?', 'How would you describe your gender?', 'Are you living with a disability or a long-term condition? If so how would you describe this?']]

def lowercase():
    df['Are you living with a disability or a long-term condition? If so how would you describe this?'] = df['Are you living with a disability or a long-term condition? If so how would you describe this?'].str.lower()
lowercase()

def encode_disability(df, **kwds):

    key = kwds['key']

    if df[key] == "no":
        return 1
    else:
        return 0

df["disability-encoded"] = df.apply(encode_disability, axis=1, key="Are you living with a disability or a long-term condition? If so how would you describe this?")
df

# def test_disability():

#     print(df['disability-encoded'].value_counts())

# test_disability()

,Where are you based?,Which age range are you in?,How would you describe your gender?,Are you living with a disability or a long-term condition? If so how would you describe this?,disability-encoded
0,Medway,70-79,Male,after affects of cancer,0
1,Medway,60-69,Male,mental health condition - depression.,0
2,Medway,60-69,Male,"alcohol dependent, stoma bag.",0
3,Medway,70-79,Female,"copd, mental health condition - depression.",0
4,Medway,40-49,Female,yes but not want to give any info.,0
...,...,...,...,...,...
174,Medway,50-59,Male,no,1
175,Medway,60-69,Male,no,1
176,Medway,60-69,Female,no,1
177,Medway,70-79,Female,no,1
178,Medway,70-79,Female,no,1